require: 
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - 'db/**/*'
    - 'script/*'
    - 'bin/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'

IndentationConsistency:
  EnforcedStyle: 'indented_internal_methods'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ClassLength:
  Max: 210

Metrics/ParameterLists:
  Max: 6

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Max: 140

  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 65

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

# TEMP: private and def foo() are at the same indentation level
# This should NOT cause an offense but it does. ¯\_(ツ)_/¯
# https://rubocop.readthedocs.io/en/latest/cops_layout/
Layout/IndentationWidth:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/*'
